FROM node:18-alpine AS build
WORKDIR /app
COPY backend/package*.json ./
RUN npm install --include=dev
COPY backend/tsconfig.json ./
COPY backend/src ./src
RUN npm run build

FROM node:18-alpine
WORKDIR /app
COPY backend/package*.json ./
RUN npm install --omit=dev
COPY --from=build /app/dist ./dist
EXPOSE 3000
CMD ["node", "dist/server.js"]
